import { motion } from 'framer-motion'
import ReactMarkdown from 'react-markdown'
import { ExternalLink, FileText, BookOpen, Copy, Check, Download, Share2, Volume2, StopCircle, Printer, Maximize2, Minimize2 } from 'lucide-react'
import { useState, useEffect } from 'react'
import type { ResearchResponse } from '../types'
import { KnowledgeGraph } from './KnowledgeGraph'
import { ErrorBoundary } from './ErrorBoundary'

interface Props {
  data: ResearchResponse
}

export function ReportView({ data }: Props) {
  const [copied, setCopied] = useState(false)
  const [showGraph, setShowGraph] = useState(true)
  const [isSpeaking, setIsSpeaking] = useState(false)
  const [speechSupported, setSpeechSupported] = useState(false)
  const [isFullscreen, setIsFullscreen] = useState(false)

  useEffect(() => {
    setSpeechSupported('speechSynthesis' in window)
    return () => {
      window.speechSynthesis.cancel()
    }
  }, [])

  const handleCopy = () => {
    navigator.clipboard.writeText(data.final_report || '')
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  const handleDownload = () => {
    const blob = new Blob([data.final_report || ''], { type: 'text/markdown' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = 'research-report.md'
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
  }

  const toggleSpeech = () => {
    if (isSpeaking) {
      window.speechSynthesis.cancel()
      setIsSpeaking(false)
    } else {
      const utterance = new SpeechSynthesisUtterance(data.final_report || "No content to read.")
      utterance.onend = () => setIsSpeaking(false)
      utterance.rate = 1.1
      window.speechSynthesis.speak(utterance)
      setIsSpeaking(true)
    }
  }

  return (
    <motion.div 
      initial={{ opacity: 0, y: 40 }}
      animate={{ opacity: 1, y: 0 }}
      className={`grid grid-cols-1 lg:grid-cols-[1fr_350px] gap-8 mt-8 ${isFullscreen ? 'fixed inset-0 z-50 bg-slate-50 dark:bg-slate-950 p-8 overflow-y-auto' : ''}`}
    >
      <div className="space-y-6 min-w-0">
        {/* Toolbar */}
        <div className="sticky top-0 z-30 bg-white/80 dark:bg-slate-900/80 backdrop-blur-md border border-slate-200 dark:border-slate-800 rounded-2xl p-2 shadow-sm flex items-center justify-between flex-wrap gap-2">
          <div className="flex items-center gap-3 px-2">
            <div className="p-2 bg-indigo-50 dark:bg-indigo-900/30 rounded-lg">
              <FileText className="w-5 h-5 text-indigo-600 dark:text-indigo-400" />
            </div>
            <div>
              <h2 className="text-sm font-bold text-slate-800 dark:text-slate-200">Research Report</h2>
              <p className="text-xs text-slate-500 dark:text-slate-400">Generated by Auto Researcher</p>
            </div>
          </div>

          <div className="flex items-center gap-1">
            {speechSupported && (
              <button 
                onClick={toggleSpeech}
                title={isSpeaking ? "Stop Reading" : "Read Aloud"}
                className={`p-2 rounded-lg transition-all ${isSpeaking ? 'bg-indigo-100 text-indigo-700 dark:bg-indigo-900/50 dark:text-indigo-300 animate-pulse' : 'text-slate-500 hover:bg-slate-100 dark:text-slate-400 dark:hover:bg-slate-800'}`}
              >
                {isSpeaking ? <StopCircle className="w-4 h-4" /> : <Volume2 className="w-4 h-4" />}
              </button>
            )}
            <div className="w-px h-6 bg-slate-200 dark:bg-slate-700 mx-1" />
            <button 
              onClick={() => setShowGraph(!showGraph)}
              title="Toggle Knowledge Graph"
              className={`p-2 rounded-lg transition-all ${showGraph ? 'bg-indigo-50 text-indigo-600 dark:bg-indigo-900/30 dark:text-indigo-400' : 'text-slate-500 hover:bg-slate-100 dark:text-slate-400 dark:hover:bg-slate-800'}`}
            >
              <Share2 className="w-4 h-4" />
            </button>
            <button 
              onClick={handleDownload}
              title="Download Markdown"
              className="p-2 text-slate-500 hover:bg-slate-100 dark:text-slate-400 dark:hover:bg-slate-800 rounded-lg transition-colors"
            >
              <Download className="w-4 h-4" />
            </button>
            <button 
              onClick={handleCopy}
              title="Copy to Clipboard"
              className="p-2 text-slate-500 hover:bg-slate-100 dark:text-slate-400 dark:hover:bg-slate-800 rounded-lg transition-colors"
            >
              {copied ? <Check className="w-4 h-4 text-green-500" /> : <Copy className="w-4 h-4" />}
            </button>
            <button 
              onClick={() => setIsFullscreen(!isFullscreen)}
              title={isFullscreen ? "Exit Fullscreen" : "Fullscreen"}
              className="p-2 text-slate-500 hover:bg-slate-100 dark:text-slate-400 dark:hover:bg-slate-800 rounded-lg transition-colors hidden md:block"
            >
              {isFullscreen ? <Minimize2 className="w-4 h-4" /> : <Maximize2 className="w-4 h-4" />}
            </button>
          </div>
        </div>

        {showGraph && (
          <motion.div 
            initial={{ opacity: 0, height: 0 }}
            animate={{ opacity: 1, height: 'auto' }}
            exit={{ opacity: 0, height: 0 }}
             className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-2xl p-1 shadow-sm overflow-hidden relative group"
          >
            <div className="absolute top-3 left-4 z-10 bg-white/90 dark:bg-slate-900/90 backdrop-blur px-2 py-1 rounded text-xs font-bold text-slate-500 uppercase tracking-wider border border-slate-200 dark:border-slate-800">
              Knowledge Graph
            </div>
            <ErrorBoundary>
             <KnowledgeGraph 
               topic={data.topic || "Research Topic"} 
               sources={Array.isArray(data.sources) ? data.sources : []} 
               graphData={data.graph_data}
             />
            </ErrorBoundary>
          </motion.div>
        )}
        
        <div className="prose prose-slate dark:prose-invert 
          prose-headings:font-bold prose-headings:tracking-tight
          prose-h1:text-3xl prose-h1:text-indigo-950 dark:prose-h1:text-indigo-100 
          prose-h2:text-xl prose-h2:text-indigo-900 dark:prose-h2:text-indigo-200 prose-h2:border-b prose-h2:border-slate-200 dark:prose-h2:border-slate-800 prose-h2:pb-2 prose-h2:mt-8
          prose-h3:text-lg prose-h3:text-indigo-800 dark:prose-h3:text-indigo-300
          prose-a:text-indigo-600 dark:prose-a:text-indigo-400 hover:prose-a:text-indigo-500 dark:hover:prose-a:text-indigo-300 prose-a:no-underline hover:prose-a:underline
          prose-blockquote:border-l-4 prose-blockquote:border-indigo-400 dark:prose-blockquote:border-indigo-600 prose-blockquote:bg-slate-50 dark:prose-blockquote:bg-slate-800/50 prose-blockquote:py-2 prose-blockquote:px-4 prose-blockquote:rounded-r-lg prose-blockquote:italic
          prose-code:text-indigo-600 dark:prose-code:text-indigo-300 prose-code:bg-indigo-50 dark:prose-code:bg-indigo-900/30 prose-code:px-1.5 prose-code:py-0.5 prose-code:rounded-md prose-code:font-mono prose-code:text-sm
          prose-pre:bg-slate-900 dark:prose-pre:bg-slate-950 prose-pre:border prose-pre:border-slate-800 prose-pre:shadow-lg
          prose-li:marker:text-indigo-400
          prose-img:rounded-xl prose-img:shadow-md
          max-w-none bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-2xl p-8 md:p-12 shadow-sm">
          <ReactMarkdown>{data.final_report || '*No report content available.*'}</ReactMarkdown>
        </div>
      </div>

      <div className="space-y-6">
        <div className="bg-slate-100 dark:bg-slate-800/50 rounded-2xl p-6 border border-slate-200 dark:border-slate-800 sticky top-24">
          <h3 className="text-sm font-bold flex items-center gap-2 text-slate-800 dark:text-slate-200 uppercase tracking-wider mb-4">
            <BookOpen className="w-4 h-4 text-indigo-500" />
            References ({ (data.sources || []).length })
          </h3>
          
          <div className="space-y-3 max-h-[calc(100vh-200px)] overflow-y-auto custom-scrollbar pr-2">
            {(data.sources || []).map((source, i) => (
              <motion.a
                key={i}
                href={source}
                target="_blank"
                rel="noreferrer"
                initial={{ opacity: 0, x: 20 }}
                animate={{ opacity: 1, x: 0 }}
                transition={{ delay: i * 0.05 }}
                className="block group p-3 bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-700 hover:border-indigo-400 dark:hover:border-indigo-500 rounded-xl transition-all duration-200 shadow-sm hover:shadow-md hover:-translate-y-0.5"
              >
                <div className="flex items-start justify-between gap-2 mb-1">
                  <span className="inline-flex items-center justify-center w-5 h-5 rounded-full bg-slate-100 dark:bg-slate-800 text-[10px] font-bold text-slate-500 group-hover:bg-indigo-100 dark:group-hover:bg-indigo-900 group-hover:text-indigo-600 dark:group-hover:text-indigo-400 transition-colors">
                    {i + 1}
                  </span>
                  <ExternalLink className="w-3 h-3 text-slate-300 dark:text-slate-600 group-hover:text-indigo-400 transition-colors" />
                </div>
                <p className="text-xs text-slate-600 dark:text-slate-400 line-clamp-2 break-all font-medium group-hover:text-slate-900 dark:group-hover:text-slate-200 transition-colors">
                  {source}
                </p>
              </motion.a>
            ))}
            
            {(data.sources || []).length === 0 && (
              <div className="p-6 text-center border-2 border-dashed border-slate-200 dark:border-slate-700 rounded-xl text-slate-400 text-xs">
                No sources cited in this report.
              </div>
            )}
          </div>
        </div>
      </div>
    </motion.div>
  )
}
